name: lint, test, build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v2
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod
        run: npm run build:prod
      - name: lint ts
        run: npm run lint
      - name: lint css
        run: npm run stylelint
      - name: unit tests
        run: npm run test:unit
      - name: build storybook
        run: npm run storybook:build

