name: lint, test, build
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [19.x]

    steps:
      - uses: actions/checkout@v3
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: npm install
      - name: build prod
        run: npm run build:prod
        if: always()
      - name: lint ts
        run: npm run lint
        if: always()
      - name: lint css
        run: npm run stylelint
        if: always()
      - name: unit tests
        run: npm run test:unit
        if: always()
      - name: build storybook
        run: npm run storybook:build
        if: always()
      # - name: screenshot tests
      #   run: npm run test:ui:ci
      #   if: always()

